### ISSUE TITLE
remove uilabel, uitype, tooltip, alias, etc. from docs

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclus.github.com#144]
I currently see the following

![tmp1](https://cloud.githubusercontent.com/assets/1392657/7684137/6d0afa60-fd49-11e4-9de7-b26b7bdcf3e6.png)

With the (very nice) example xml snippets, I think all of these (now ugly and mostly UI-specific/tangential) other categories can go away.

**Comment by rwcarlsen** [comment]
Agree.

**Comment by rwcarlsen** [comment]
Well - maybe uitype is still useful - it unambiguously identifies commodity
and nuclide data types.

**Comment by gidden** [comment]
Agreed. I think it probably will have a better home somewhere else (docs for arche devs to use the UI maybe?), but that doesn't exist anywhere yet.
