### ISSUE TITLE
v1.3.0 figshare citation not on website

### ISSUE THREAD

**Issue by scopatz** [cyclus/cyclus.github.com#164]
namely this page - http://fuelcycle.org/cite/index.html

**Comment by rwcarlsen** [comment]
I don't even think we have a DOI yet.

**Comment by rwcarlsen** [comment]
sorry - clicked close accidently.

**Comment by rwcarlsen** [comment]
Dangit :/

**Comment by gidden** [comment]
There are 1.3.0 DOIs for all projects (e.g.. cyclus -
http://figshare.com/preview/_preview/1427429). I may have forgotten to
update the website. I'll look at it tomorrow.

On Mon, Jul 20, 2015 at 6:25 PM, Robert Carlsen <notifications@github.com>
wrote:

> Dangit :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus.github.com/issues/164#issuecomment-123088345>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
Fixed with 39816015dc9

**Comment by rwcarlsen** [comment]
Thanks @gidden!
