### ISSUE TITLE
Cyclus Job stuck on Queued 

### ISSUE THREAD

**Issue by chiudaniels** [cyclus/cyclus.github.com#276]
When trying to execute the tutorial job on the cloud, the job is stuck on queued. When I check the http://cycrun.fuelcycle.org/ url, I see my job is queued. I also see that the same job I executed a few days ago has the status failed with the error code:

>  ERROR(core  ):Document failed schema validation
> Entity: line 1: element capacity: Relax-NG validity error : Type double doesn't allow value ''
> Entity: line 1: element capacity: Relax-NG validity error : Error validating datatype double
> Entity: line 1: element capacity: Relax-NG validity error : Element capacity failed to validate content
> Entity: line 1: element Sink: Relax-NG validity error : Invalid sequence in interleave
> Entity: line 1: element Sink: Relax-NG validity error : Element Sink failed to validate content
> Relax-NG validity error : Extra element facility in interleave
> Entity: line 1: element facility: Relax-NG validity error : Element simulation failed to validate content
> exit status 1

**Comment by bam241** [comment]
@chiudaniels I fixed the worker issues, sorry about that.

about your input:
around line 205 and 282
you have `<capacity/>` which causes the simulation to fail

xml tags should appear as `<capacity>XX</capacity>` where `XX` should be replaced with your information.

BaM
