### ISSUE TITLE
build issue - Could not import extension numpydoc

### ISSUE THREAD

**Issue by jbae11** [cyclus/cyclus.github.com#290]
```
Extension error:
Could not import extension numpydoc (exception: cannot import name 'Directive')
make: *** [Makefile:66: html] Error 2
```

**Comment by jbae11** [comment]
Downgrading `sphinx` to 1.6.x solves this issue.
`conda install sphinx=1.6`

**Comment by bam241** [comment]
I think I read something about this: "Directive was removed from sphinix package from version 1.7"
from https://github.com/rtfd/readthedocs.org/issues/4057

**Comment by jbae11** [comment]
yup. I was able to build it!
