### ISSUE TITLE
Update User Tutorial to include XML input files

### ISSUE THREAD

**Issue by abachma2** [cyclus/cyclus.github.com#305]
The link to download Cyclist on Linux is broken (takes to a broken link). but the tutorial is heavily based on the use of Cyclist. Can we modify the tutorial to include creating inputs as XML files. Similar to Issues #274 and #267.

**Comment by gonuke** [comment]
There is a pending PR #293 that I think was awaiting finalization by @cyclus/uiuc

**Comment by abachma2** [comment]
Missed that one. It looks like it has been approved by @katyhuff and is still awaiting 2 reviewers. I am okay with closing this issue once that PR goes through.

**Comment by abachma2** [comment]
Closing since PR #293 has been merged.
