### ISSUE TITLE
inconsistency in tutorial 

### ISSUE THREAD

**Issue by di212** [cyclus/cyclus.github.com#311]
Hi, here http://fuelcycle.org/user/tutorial/add_proto.html
the prototype has to be located:
"Once complete, append this facility under the commodity section and before the recipe section of your input file."

but in the final input file http://fuelcycle.org/user/tutorial/full_input_1.html it goes after recipes. 
which one is correct. 

Also, nothing was mentioned about the location of regions and institutions in the input file here http://fuelcycle.org/user/tutorial/add_reg_inst.html#id1

**Comment by abachma2** [comment]
The order of the sections in your input file is not of major consequence, I think the tutorial mentions that near the beginning.
