### ISSUE TITLE
Fix sidebar menu for archetype tutorial

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus.github.com#320]
The sidebar menu has a link to a developers tutorial that is broken.  Navigating through the developers guide shows two parallel tutorials, one is C++ and the other is python.

**Comment by bennibbelink** [comment]
Is the link still in the sidebar? I only see it under the "Learn More" heading on the homepage, and that one appears to be working.

**Comment by bennibbelink** [comment]
Nevermind, working on fixing the sidebar now and I see that the archetype tutorial links should be in the sidebar.

**Comment by bennibbelink** [comment]
@gonuke can you confirm whether this issue persists?  The links are working for me on the published site.

**Comment by gonuke** [comment]
Looks like I fixed this in #323 that was merged several weeks ago
