### ISSUE TITLE
Add information about ARFC archetypes

### ISSUE THREAD

**Issue by abachma2** [cyclus/cyclus.github.com#327]
The Advanced Reactors and Fuel Cycles (ARFC) group at UIUC has a few different archetypes that others might be interested. They should be added to the website in the "Third party archetypes" section of the main page. 

Nathan Added locations where they are listed:
[Cyclus User Guide](http://fuelcycle.org/user/index.html#=third-party)
[Understanding Archetypes page](http://fuelcycle.org/user/tutorial/add_arche.html)

**Comment by nuclearkatie** [comment]
[Flexicamore](https://github.com/maxschalz/flexicamore)
- Source
- Storage
- Enrichment
- Sink

[Miso_enrichment](https://github.com/Nuclear-Verification-and-Disarmament/miso_enrichment)
- MIsoEnrich
- GprReactor

**Comment by nsryan2** [comment]
D3ploy: https://github.com/arfc/d3ploy/
OpenMCyclus: https://github.com/arfc/openmcyclus/ 
Cyder: https://github.com/arfc/cyder
MBMoore: https://github.com/cnerg/mbmore

**Comment by nsryan2** [comment]
Rwc-archetypes: https://github.com/rwcarlsen/rwc-archetypes 
Peddler: https://github.com/ergs/peddler
depletion_rom: https://github.com/jbae11/depletion_rom

**Comment by nsryan2** [comment]
Rwc-archetypes: https://github.com/rwcarlsen/rwc-archetypes 
Peddler: https://github.com/ergs/peddler

**Comment by nuclearkatie** [comment]
The [Oct 2017](http://fuelcycle.org/newsletters/oct2017.html) and [May 2018](http://fuelcycle.org/newsletters/may2018.html) newsletters have a bit of information about several third party modules. We should check and at least keep the user guide updated with the info here
