### ISSUE TITLE
Renaming `master` to `main`

### ISSUE THREAD

**Issue by munkm** [cyclus/cyclus.github.com#338]
This issue is based on [this](https://github.com/cyclus/cyclus.github.com/pull/332#issuecomment-1957524425) comment from another PR. 

Pros: 
* This rename is in line with current development best practices
Cons: 
* We need to update all references of `master` in our documentation and on the website
* We need to make sure all users and developers are notified about the change as it could/will affect their workflows.

**Comment by gonuke** [comment]
A `main` branch has been created and is now being used to published the rendered content using Github Pages

**Comment by munkm** [comment]
excellent! I'll close this as resolved, then.
