### ISSUE TITLE
Publish site using Github Actions

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus.github.com#344]
Is there any interest to move the publishing process to CI?

What I'm envisioning is:
- "build/test" workflow that generates the site and uploads the html dir as a build artifact (which reviewers can download to serve locally)
- "publish" workflow that runs on merge to source and pushes generated html to master

I'm skipping over lots of detail but I see value in automating this process so there's less responsibility on the contributor to perform steps locally.  Any thoughts? Comments? Objections?

**Comment by gonuke** [comment]
Can you find some references for best practice on this?  I am definitely interested in this, but my prior searches came up a little mixed.  Also, from my point of view, downloading the artifact is on par with running a local Docker build.  In addition, a local docker build gives me a tighter feedback loop on edits.  I think the biggest benefit is probably for reviewers and not contributors.

**Comment by bennibbelink** [comment]
This [page](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site) in the Github Docs outlines the process of deploying via workflows. Sounds like the workflow should consist of:
1. Checkout the repo
2. Do whatever we need to build the site
3. Use the [`actions/upload-pages-artifact`](https://github.com/actions/upload-pages-artifact) action to upload a tarball of the built site
4. Use the [`actions/deploy-pages`](https://github.com/actions/deploy-pages) action to deploy the uploaded artifact

It is unclear to me whether we need to maintain a branch that has the built site (`master` in our case, soon to be `main`).

-----------------------------

>  a local docker build gives me a tighter feedback loop on edits. I think the biggest benefit is probably for reviewers and not contributors.

Can't argue with the feedback loop (sidenote: I will update it to use our newer GHCR image).  I more so mean that by having GitHub help facilitate the publishing process there is less legwork for contributors (even if it is automated by the Makefile).  I see two advantages: 
1. Less manual steps means (hopefully) less room for error.
2. If the contributor workflow to update the website is less involved then (hopefully!!) we will do a better job of keeping it up to date.

**Comment by bennibbelink** [comment]
Played around with this on my fork.  In the repo Pages settings I changed the Source from "Deploy from a branch" to "Github Actions".  I then made a [test PR](https://github.com/bennibbelink/cyclus.github.com/pull/1) and merged it to evaluate the workflow.  The site was published with no issues - https://bennibbelink.github.io/cyclus.github.com/

The [workflow](https://github.com/bennibbelink/cyclus.github.com/blob/source/.github/workflows/build_publish.yml) is very straightforward as well.  Ready to PR on the upstream if we want to move forward with this.

**Comment by gonuke** [comment]
I think we should move forward with this, particularly given the GH guidance for non-Jekyll builds.

That said, this relies in our custom build docker images having the right config. We probably want that to be part of the workflow somewhere? I'm not sure all the images have Sphinx.  I saw that install in your sample build, but I didn't really see where that happened in your sample PR.

**Comment by bennibbelink** [comment]
Moving this conversation to #349.
