### ISSUE TITLE
Sidebar is broken 

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus.github.com#350]
The sidebar no longer shows everything that it should.  This may(?) be related to the Sphinx version and/or the theme we are using.

**Comment by gonuke** [comment]
Some things on this: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_sidebars

Also search for `sidebarsearch` on this page: https://www.sphinx-doc.org/en/master/development/templating.html (Deprecated since 1.0)
