### ISSUE TITLE
Update `README` and `Makefile` to reflect the fact that we build with an action

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclus.github.com#357]
We now build with a GitHub action instead of publishing from `main`.  (@bennibbelink - does that action push to `main` or to some unidentified place in the cloud that we don’t need to know about?)

To avoid confusion, we should update the instructions and perhaps streamline the Makefile to remove things we no longer need (or that no longer have any effect).

**Comment by bennibbelink** [comment]
The action does not push to `main`, it deploys to the `github-pages` environment according to the [documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site).  On my fork I can see details about the deployment environment if I navigate to the Pages Settings and click on the hyperlinked "github-pages" under the "Build and deployment" heading.

I will work on making appropriate changes to the README and Makefile.

**Comment by gonuke** [comment]
We may also want to delete the `main` branch or decide to move `source` to `main`?

**Comment by bennibbelink** [comment]
Either works.  I might lean toward just deleting `main` - I think maintaining the `source` branch is more clear that the branch contains "source" files and not a built website ready for serving.
