### ISSUE TITLE
DOI for v1.6.0

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus.github.com#368]
[CEP4](http://fuelcycle.org/cep/cep4.html) dictates that we create a DOI for a Cyclus release.  There are detailed instructions in the document, but I'd like to tag in some people who have may have done this before @gonuke @abachma2.  Does it matter who creates the DOI / is there a figshare account associated with the Cyclus organization?

**Comment by abachma2** [comment]
I'm not sure about figshare, but I've used Zenodo in the past for creating DOIs. Happy to do that if we don't have a preferes method by the org, just let me know who to include as authors and any ORCIDS.

**Comment by gonuke** [comment]
We may need to try one of the release utilities to confirm who the authors are per CEP4

**Comment by bennibbelink** [comment]
I didn't see anything in the release utilities for this, but I got a list of users via `git log 1.5.0..1.6.0 --pretty=format:"%ae" | sort -u` (and %an).  I've removed some duplicate emails and filled in some names.  I am fairly confident about most of these, but please review and make corrections to this comment if I'm wrong.  I have not sorted them alphabetically yet.


45630975+a-co@users.noreply.github.com - duplicate for Anna Caldwell-Overdier?
56325916+yvrob@users.noreply.github.com - **Yves Robert**
58850267+maxschalz@users.noreply.github.com - **Max Schalz**
aandrsn3@illinois.edu - **Aaron Anderson**
abachmann@anl.gov - **Amanda Bachmann**
acaldwel@wellesley.edu - **Anna Caldwell-Overdier**
adityab@iitb.ac.in - **Aditya Bhosale**
bam241@users.noreply.github.com - **Baptiste Mouginot**
bnibbs@vt.edu - **Ben Nibbelink**
dean.krueger@wisc.edu - **Dean Kreuger**
dwang0127@gmail.com - **Di Wang**
eredfoot@gmail.com - **Emma Redfoot**
flanflanagan@gmail.com - **Robert Flanagan**
gtpark96@gmail.com - **Gyutae Park**
gwendolynchee95@gmail.com - **Gwendolyn Chee**
jbae11@illinois.edu - **Jin Whan Bae**
katyhuff@users.noreply.github.com - **Kathryn Huff**
kiplk2@illinois.edu - **Kip Kleimenhagen**
lewin@lewin-bormann.info - **Lewin Bormann**
mbmcgarry@wisc.edu - **Meghan McGarry**
mummah@lanl.gov - **Katie Mummah**
paul.wilson@wisc.edu - **Paul Wilson**
rhodge@email.sc.edu - **Ryan Hodge**
robi11143211@gmail.com - ?
scopatz@gmail.com - **Anthony Scopatz**
snehalchandan25@gmail.com - **Snehal Chandan**
stomps@wisc.edu - **Jordan Stomps**

**Comment by gonuke** [comment]
I've started an entry on Figshare, but getting correct identifiers for all of these authors may prove challenging....

**Comment by bennibbelink** [comment]
A Figshare entry has been made for the 1.6.0 release: https://figshare.com/articles/software/Cyclus_v1_6_0/25752558

Thanks for taking care of this @gonuke, closing this issue.

**Comment by abachma2** [comment]
We should add this DOI into the publications list on the website. Should I make a separate issue for that? Also, did we make a DOI for the Cycamore and Cymetric releases?

**Comment by bennibbelink** [comment]
We did not make a DOI for Cycamore or Cymetric, reopening this issue for those tasks

- [x] Publish Cycamore v1.6.0 DOI
- [x] Publish Cymetric v1.6.0 DOI

I would make a separate issue for adding these to the website, thanks for bringing that up @abachma2

**Comment by abachma2** [comment]
Has anyone gotten around to taking care of this? A Cycamore v1.6 citation would be really useful for something I'm working on.

**Comment by bennibbelink** [comment]
I don't believe it has been made yet...

This is the list of Cycamore contributors for v1.6.0 as far as I can tell:
Amanda Bachmann
Jin Whan Bae
Anna Caldwell-Overdier
Gwendolyn Chee
Roberto Fairhurst Agosta
Robert Flanagan
Adam Glenn
Katy Huff
Baptiste Mouginot
Katie Mummah
Ben Nibbelink
Arrielle Opotowsky
Gyutae Park
Max Schalz
Anthony Scopatz
Jordan Stomps
Sonata Vilmantė
Paul Wilson
robi111432 (?)

@abachma2 how familiar are you with Figshare? I can take a stab at making an entry but it may be a learning process

**Comment by abachma2** [comment]
I have never made a new item on figshare, so it sounds like it would take a similar amount of time for either of us to do it.

**Comment by bennibbelink** [comment]
Ok I'll give it a shot and update this issue with my progress

**Comment by bennibbelink** [comment]
Cycamore item has been published - https://figshare.com/articles/software/Cycamore_v1_6_0/26107069.  Let me know if you see any issues with it, I think it's editable.

I'll make one for Cymetric as well. Cymetric authors for reference:

Amanda Bachmann
Anna Caldwell-Overdier
Gwendolyn Chee
Robert Flanagan
Louis Hartono
Katy Huff
Baptiste Mouginot
Katie Mummah
Ben Nibbelink
Anthony Scopatz
Jordan Stomps
Paul Wilson

**Comment by abachma2** [comment]
Great! Thanks for getting that done @bennibbelink!

**Comment by bennibbelink** [comment]
Cymetric entry is published - https://figshare.com/articles/software/Cymetric_v1_6_0/26107180

I will leave you all to close this issue after you get a chance to review these Figshare entries

**Comment by abachma2** [comment]
It all looks good to me. I'll leave this open for a bit in case @gonuke has any comments. I plan to close this next Friday (7/5) if there are no more comments.

**Comment by gonuke** [comment]
Should we record the actual DOI's anywhere? e.g. https://doi.org/10.6084/m9.figshare.25752558.v1 for Cycamore 1.6.0?

**Comment by abachma2** [comment]
Yes. That's part of #371
