### ISSUE TITLE
Update publications

### ISSUE THREAD

**Issue by abachma2** [cyclus/cyclus.github.com#371]
The publications list on `source/cite/index.rst` should be updated to include:
- [x] Cyclus v1.6 DOI
- [x] Cycamore v1.6 DOI
- [x] Cymetric V1.6 DOI
- [x] "[Fundamental concepts in the Cyclus nuclear fuel cycle simulation framework"](https://www.sciencedirect.com/science/article/pii/S0965997816300229) -- this feels like the most complete summary of the Cyclus architecture that is cited in literature
- [x] ["Standardized verification of the Cyclus fuel cycle simulator"](https://www.sciencedirect.com/science/article/pii/S0306454919300179)

Questions about the page (hopefully @gonuke, @katyhuff, @munkm, and/or @bam241 can answer):
- Are the publications in any particular order currently? If not, I suggest re-ordering them to be in reverse chronological order. 
- Are we okay with me adding the March 2024 Cyclus meeting agenda to the page (similar to the 10/2014 meeting at ANL)?
- Are the "Citing Cyclus" citations in any particular order? If not, then I suggest re-ordering them to reverse chronological order. 

Closing this issue addresses some of the items in #337.

**Comment by gonuke** [comment]
@abachma2 - I think this is all done - can you confirm and close?

**Comment by abachma2** [comment]
Yes, this can be closed now that #374 is merged.
