### ISSUE TITLE
Package type not known to website

### ISSUE THREAD

**Issue by nuclearkatie** [cyclus/cyclus.github.com#373]
Adding a type to the [cyclus preprocessor](https://github.com/cyclus/cyclus/blob/30669380be2e97bb559317b6f69ff76b34694531/cli/cycpp.py#L4) in cyclus isn't enough,  must also be declared here

Fix by adding `packages`to cyclusagents.py

(will do in conjunction with forthcoming PR including documentation on packaging)

**Comment by gonuke** [comment]
I think for forgot to indicate where "here" was that it must also be declared?

**Comment by gonuke** [comment]
> I think for forgot to indicate where "here" was that it must also be declared?

I see it now
