### ISSUE TITLE
API docs are not visible

### ISSUE THREAD

**Issue by bennibbelink** [cyclus/cyclus.github.com#388]
I unpublished the Pages sites for cyclus/cyclus and cyclus/cycamore, so in theory their respective api docs should be accessible from a subfolder of the cyclus/cyclus.github.com build.  

The error that you see when you access https://fuelcycle.org/cyclus ("There isn't a Github Pages site here.") is different than if you try to access a page that doesn't exist (e.g. https://fuelcycle.org/fakepage - "The site configured at this address does not contain the requested file."). This leads me to believe it's a DNS issue.  

I'm wondering if we have [verified the domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages) `fuelcycle.org/cyclus` and because of that - the files hosted by cyclus.github.com at a subpath of `/cyclus` are blocked from being accessed.  @gonuke what do you see in the Pages settings for the cyclus organization?

**Comment by gonuke** [comment]
I verified the domain, but it seems to have made things worse..

**Comment by gonuke** [comment]
I reset a few things and redeployed by rerunning the last successful push to source it seems to have worked...

**Comment by gonuke** [comment]
Maybe this should be a separate issue, but I think we should have:
* a link to the top level of fuelcycle.org on the API docs main page and/or in a footer
* a landing page for fuelcycle.org/cyclus - fuelcycle.org/cyclus/api works, but the former is a legit 404

**Comment by bennibbelink** [comment]
Sorry I wasn't responsive while you were figuring this out.  Whatever change worked for cyclus, could you do the same for cycamore? 

As for your points:

> a link to the top level of fuelcycle.org on the API docs main page and/or in a footer

I agree, I'll make an issue

> a landing page for fuelcycle.org/cyclus - fuelcycle.org/cyclus/api works, but the former is a legit 404

We can just put the docs at /cyclus and /cycamore, them being at /cyclus/api is a remnant of the old publishing procedure.  I'll make an issue for this as well.

**Comment by gonuke** [comment]
> Sorry I wasn't responsive while you were figuring this out. 

No worries - you do have a day job...

> Whatever change worked for cyclus, could you do the same for cycamore?

Done

> > a landing page for fuelcycle.org/cyclus - fuelcycle.org/cyclus/api works, but the former is a legit 404
> 
> We can just put the docs at /cyclus and /cycamore, them being at /cyclus/api is a remnant of the old publishing procedure. I'll make an issue for this as well.

:+1:

Feel free to close this when ready...

**Comment by bennibbelink** [comment]
Thanks @gonuke. Closing this issue - Cycamore api docs are accessible at https://fuelcycle.org/cycamore/api
